/**
 * Reports.jsx – Engineering report generation with PDF download.
 */
import { useState } from "react";
import { computeGridHealth, computeFaultRisk, getRiskLevel, generateXAIFactors, generateWaveform } from "../simulation.js";
import { api } from "../api.js";

export default function Reports({ scenario, lastClassification, lastDiagnosis }) {
  const [generating, setGenerating] = useState(false);
  const [reportGenerated, setReportGenerated] = useState(false);
  const [includeWaveform, setIncludeWaveform] = useState(true);
  const [includeXAI, setIncludeXAI] = useState(true);

  const health = computeGridHealth(scenario);
  const risk = computeFaultRisk(scenario);
  const riskLevel = getRiskLevel(risk);
  const xaiFacts = generateXAIFactors(scenario);

  // PDF via backend if record selected, else client-side markdown
  const generateReport = async () => {
    setGenerating(true);
    try {
      // Try backend PDF first
      if (lastClassification?.record_id) {
        await api.downloadReportPdf(lastClassification.record_id, lastDiagnosis);
        setReportGenerated(true);
        return;
      }

      // Client-side text report
      const lines = [];
      lines.push("# GridGuard Fault Report");
      lines.push(`\n**Generated:** ${new Date().toISOString()}`);
      lines.push(`**Source:** Simulation Mode 🧪`);
      lines.push("\n---\n");
      lines.push("## Input Parameters");
      lines.push(`| Parameter | Phase A | Phase B | Phase C |`);
      lines.push(`|---|---|---|---|`);
      lines.push(`| Voltage (V) | ${scenario.Va} | ${scenario.Vb} | ${scenario.Vc} |`);
      lines.push(`| Current (A) | ${scenario.Ia} | ${scenario.Ib} | ${scenario.Ic} |`);
      lines.push(`| Frequency (Hz) | ${scenario.frequency} | | |`);
      lines.push(`| Power Factor | ${scenario.powerFactor} | | |`);
      lines.push(`| V-Unbalance (%) | ${scenario.voltageUnbalance} | | |`);
      lines.push(`| I-Unbalance (%) | ${scenario.currentUnbalance} | | |`);
      lines.push("\n## Fault Analysis");
      lines.push(`- **Fault Type:** ${scenario.faultType || "NONE"}`);
      lines.push(`- **Affected Phase:** ${scenario.affectedPhase || "None"}`);
      lines.push(`- **Severity:** ${scenario.severity || "Normal"}`);
      lines.push(`- **Fault Location:** ${scenario.faultLocation != null ? scenario.faultLocation.toFixed(1) + "% of line (SIMULATED)" : "N/A"}`);
      lines.push("\n## Grid Health");
      lines.push(`- **Grid Health Score:** ${health}/100`);
      lines.push(`- **Fault Risk:** ${risk.toFixed(0)}%`);
      lines.push(`- **Risk Level:** ${riskLevel.label}`);
      if (includeXAI) {
        lines.push("\n## AI Explanation");
        xaiFacts.forEach((f) => lines.push(`- **${f.name}** (${f.impact}): ${f.direction} ${f.value} — ${f.description}`));
      }
      lines.push(`\n---\n*Generated by GridGuard v2.0. Simulation data only. Not real grid measurements.*`);

      const content = lines.join("\n");
      const blob = new Blob([content], { type: "text/markdown" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `gridguard_report_${Date.now()}.md`;
      a.click();
      URL.revokeObjectURL(url);
      setReportGenerated(true);
    } catch (e) {
      console.error(e);
    } finally {
      setGenerating(false);
    }
  };

  const health_color = health >= 70 ? "#3ADC8C" : health >= 40 ? "#F5A623" : "#FF5470";

  return (
    <div className="space-y-5 p-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="font-display font-semibold text-xl">Engineering Report</h2>
          <p className="text-xs text-ink-muted mt-1">Generate and download a fault analysis report</p>
        </div>
        <button
          className="btn-primary"
          onClick={generateReport}
          disabled={generating}
          id="generate-report-btn"
        >
          {generating ? "⏳ Generating…" : "📄 Generate & Download Report"}
        </button>
      </div>

      {reportGenerated && (
        <div className="px-4 py-3 rounded-lg bg-signal-green/10 border border-signal-green/30 text-signal-green text-sm">
          ✅ Report generated and downloaded successfully!
        </div>
      )}

      {/* Report preview */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {/* Report content preview */}
        <div className="space-y-4">
          <div className="panel p-5">
            <div className="flex items-center gap-2 mb-4 pb-3 border-b border-border-soft">
              <svg width="28" height="20" viewBox="0 0 44 30">
                <path d="M0 15 Q 5.5 2, 11 15 T 22 15" fill="none" stroke="#2FD9D2" strokeWidth="2" />
                <path d="M0 15 Q 5.5 22, 11 15 T 22 15 T 33 15" fill="none" stroke="#F5A623" strokeWidth="2" opacity="0.8" />
                <path d="M0 15 Q 5.5 9, 11 15 T 22 15 T 33 15 T 44 15" fill="none" stroke="#8B7CF6" strokeWidth="2" opacity="0.65" />
              </svg>
              <div>
                <p className="font-display font-bold text-base">GridGuard Fault Report</p>
                <p className="text-[10px] font-mono text-ink-faint">Generated: {new Date().toLocaleString()}</p>
              </div>
              <span className="ml-auto text-[10px] font-mono px-2 py-0.5 rounded bg-signal-amber/10 border border-signal-amber/30 text-signal-amber">🧪 SIMULATION</span>
            </div>

            {/* Input params section */}
            <div className="mb-4">
              <p className="eyebrow mb-2">Input Parameters</p>
              <table className="w-full text-xs font-mono">
                <thead>
                  <tr className="text-ink-faint">
                    <td className="py-1">Parameter</td>
                    <td className="py-1 text-signal-cyan">Phase A</td>
                    <td className="py-1 text-signal-amber">Phase B</td>
                    <td className="py-1 text-signal-violet">Phase C</td>
                  </tr>
                </thead>
                <tbody className="text-ink-primary">
                  <tr><td className="py-0.5 text-ink-muted">Voltage (V)</td><td>{scenario.Va}</td><td>{scenario.Vb}</td><td>{scenario.Vc}</td></tr>
                  <tr><td className="py-0.5 text-ink-muted">Current (A)</td><td>{scenario.Ia}</td><td>{scenario.Ib}</td><td>{scenario.Ic}</td></tr>
                  <tr><td className="py-0.5 text-ink-muted">Frequency (Hz)</td><td colSpan={3}>{scenario.frequency}</td></tr>
                  <tr><td className="py-0.5 text-ink-muted">Power Factor</td><td colSpan={3}>{scenario.powerFactor}</td></tr>
                </tbody>
              </table>
            </div>

            {/* Fault analysis */}
            <div className="mb-4">
              <p className="eyebrow mb-2">Fault Analysis</p>
              <div className="grid grid-cols-2 gap-2">
                {[
                  { label: "Fault Type",    value: scenario.faultType || "NONE",       color: scenario.faultType === "NONE" ? "#3ADC8C" : "#FF5470" },
                  { label: "Affected Phase",value: scenario.affectedPhase || "None",   color: "#F5A623" },
                  { label: "Severity",      value: scenario.severity || "Normal",      color: riskLevel.color },
                  { label: "Location",      value: scenario.faultLocation != null ? `${scenario.faultLocation.toFixed(1)}% (SIM)` : "N/A", color: "#2FD9D2" },
                ].map((item) => (
                  <div key={item.label} className="bg-bg-raised rounded p-2">
                    <p className="text-[9px] text-ink-faint">{item.label}</p>
                    <p className="font-mono text-sm font-semibold mt-0.5" style={{ color: item.color }}>{item.value}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Grid health */}
            <div className="mb-4">
              <p className="eyebrow mb-2">Grid Health</p>
              <div className="flex items-center gap-4">
                <div>
                  <p className="font-mono font-bold text-3xl" style={{ color: health_color }}>{health}</p>
                  <p className="text-[10px] text-ink-faint">/ 100</p>
                </div>
                <div className="flex-1">
                  <div className="flex justify-between text-xs mb-1">
                    <span className="text-ink-muted">Fault Risk</span>
                    <span className="font-mono" style={{ color: riskLevel.color }}>{risk.toFixed(0)}% — {riskLevel.label}</span>
                  </div>
                  <div className="h-2 rounded-full bg-bg-raised overflow-hidden">
                    <div className="h-full rounded-full" style={{ width: `${risk}%`, background: riskLevel.color }} />
                  </div>
                </div>
              </div>
            </div>

            {/* AI Diagnosis from backend */}
            {lastDiagnosis && (
              <div className="mb-4">
                <p className="eyebrow mb-2">AI Diagnosis</p>
                <div className="text-xs text-ink-muted leading-relaxed whitespace-pre-wrap bg-bg-raised rounded p-3 max-h-40 overflow-y-auto">
                  {lastDiagnosis.diagnosis}
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Options + XAI */}
        <div className="space-y-4">
          <div className="panel p-5">
            <p className="eyebrow mb-3">Report Options</p>
            <div className="space-y-3">
              {[
                { id: "opt-waveform", label: "Include Waveform", value: includeWaveform, set: setIncludeWaveform },
                { id: "opt-xai",     label: "Include AI Explanation", value: includeXAI, set: setIncludeXAI },
              ].map((opt) => (
                <label key={opt.id} className="flex items-center gap-3 cursor-pointer">
                  <div
                    className={`w-10 h-5 rounded-full transition-all relative ${opt.value ? "bg-signal-cyan" : "bg-bg-raised border border-border"}`}
                    onClick={() => opt.set(!opt.value)}
                    id={opt.id}
                  >
                    <div className={`absolute top-0.5 w-4 h-4 rounded-full bg-white transition-all ${opt.value ? "left-5" : "left-0.5"}`} />
                  </div>
                  <span className="text-sm text-ink-primary">{opt.label}</span>
                </label>
              ))}
            </div>
            <div className="mt-4 pt-4 border-t border-border-soft">
              <p className="eyebrow mb-2">Export Formats</p>
              <div className="flex gap-2">
                <button className="btn-primary text-xs !px-3 !py-1.5" onClick={generateReport} disabled={generating} id="download-pdf-btn">
                  📄 {lastClassification ? "Download PDF" : "Download MD"}
                </button>
              </div>
              <p className="text-[10px] font-mono text-ink-faint mt-2">
                {lastClassification ? "PDF generated via backend API" : "Markdown report (backend offline or no record selected)"}
              </p>
            </div>
          </div>

          {/* XAI section */}
          {includeXAI && (
            <div className="panel p-5">
              <p className="eyebrow mb-3">AI Explanation</p>
              <div className="space-y-2">
                {xaiFacts.map((f, i) => (
                  <div key={i} className="p-2.5 rounded-lg bg-bg-raised border border-border-soft text-xs">
                    <span className="font-semibold text-ink-primary">{f.name}: </span>
                    <span className="font-mono" style={{ color: { Critical: "#FF5470", High: "#FF8C42", Medium: "#F5A623", Low: "#3ADC8C" }[f.impact] }}>
                      {f.direction} {f.value}
                    </span>
                    <span className="text-ink-muted"> — {f.description}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
